// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Open.Core.Web.Controllers {
    public partial class CoreController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CoreController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CoreController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult RenderUrl() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.RenderUrl);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CoreController Actions { get { return MVC.Core; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Core";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string TestHarness = "TestHarness";
            public readonly string RenderUrl = "RenderUrl";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string RenderUrl = "~/Views/Core/RenderUrl.ascx";
            public readonly string TestHarness = "~/Views/Core/TestHarness.aspx";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_CoreController: Open.Core.Web.Controllers.CoreController {
        public T4MVC_CoreController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult TestHarness() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.TestHarness);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RenderUrl(string url) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.RenderUrl);
            callInfo.RouteValueDictionary.Add("url", url);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
