//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open.TestHarness.View.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLibrary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Open.TestHarness.View.Assets.StringLibrary", typeof(StringLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string FooterPanel_Title_Output {
            get {
                return ResourceManager.GetString("FooterPanel_Title_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use: Output.Write(value);.
        /// </summary>
        public static string OutputLog_Hint {
            get {
                return ResourceManager.GetString("OutputLog_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string PropertyExplorer_ModelOption {
            get {
                return ResourceManager.GetString("PropertyExplorer_ModelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties on the DataContext (Model).
        /// </summary>
        public static string PropertyExplorer_ModelOption_ToolTip {
            get {
                return ResourceManager.GetString("PropertyExplorer_ModelOption_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PropertyExplorer_Title {
            get {
                return ResourceManager.GetString("PropertyExplorer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string PropertyExplorer_ViewOption {
            get {
                return ResourceManager.GetString("PropertyExplorer_ViewOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties on the Control (View).
        /// </summary>
        public static string PropertyExplorer_ViewOption_ToolTip {
            get {
                return ResourceManager.GetString("PropertyExplorer_ViewOption_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Assembly....
        /// </summary>
        public static string ToolTip_AddModule {
            get {
                return ResourceManager.GetString("ToolTip_AddModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run View Tests.
        /// </summary>
        public static string ToolTip_AutoRunTests {
            get {
                return ResourceManager.GetString("ToolTip_AutoRunTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Unit Tests.
        /// </summary>
        public static string ToolTip_RunUnitTests {
            get {
                return ResourceManager.GetString("ToolTip_RunUnitTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag to filter tests by.
        /// </summary>
        public static string ToolTip_TestTag {
            get {
                return ResourceManager.GetString("ToolTip_TestTag", resourceCulture);
            }
        }
    }
}
