// Open.Core.Script.js
(function(){function executeScript(){
Type.registerNamespace('Open.Core');Open.Core.Css=function(){}
Open.Core.Events=function(){}
Open.Core.DelegateUtil=function(){}
Open.Core.DelegateUtil.toCallbackString=function(callback){return 'ss.Delegate.'+ss.Delegate.createExport(callback,true);}
Open.Core.DelegateUtil.toEventCallbackString=function(callback,eventIdentifier){var $0=String.format('{0}(\'{1}\');',Open.Core.DelegateUtil.toCallbackString(callback),eventIdentifier);return 'function(e,ui){ '+$0+' }';}
Type.registerNamespace('Open.Core.UI');Open.Core.UI.HorizontalPanelResizer=function(panelId){Open.Core.UI.HorizontalPanelResizer.initializeBase(this,[panelId]);}
Open.Core.UI.HorizontalPanelResizer.prototype={$C:0,$D:0,get_minWidth:function(){return this.$C;},set_minWidth:function(value){if(value===this.$C){return;}this.$C=value;this.$F();return value;},get_maxWidthMargin:function(){return this.$D;},set_maxWidthMargin:function(value){this.$D=value;return value;},getHandles:function(){return 'e';},onInitialize:function(){this.$E();},onStopped:function(){var $0=this.getPanel();$0.css('height',String.Empty);},onWindowSizeChanged:function(){if(this.isInitialized){this.$E();}},$E:function(){this.$F();this.$10();},$F:function(){this.setResizeOption('minWidth',this.get_minWidth());},$10:function(){var $0=(this.get_hasRootContainer())?(this.getRootContainer().width()-this.get_maxWidthMargin()).toString():String.Empty;this.setResizeOption('maxWidth',$0);}}
Open.Core.UI.PanelResizerBase=function(panelId){this.panelId=panelId;$(window).bind('resize',ss.Delegate.create(this,function($p1_0){
this.onWindowSizeChanged();}));var $0=alert('blab');;}
Open.Core.UI.PanelResizerBase.prototype={add_resized:function(value){this.$0=ss.Delegate.combine(this.$0,value);},remove_resized:function(value){this.$0=ss.Delegate.remove(this.$0,value);},$0:null,$1:function(){if(this.$0!=null){this.$0.invoke(this,new ss.EventArgs());}},add_resizeStarted:function(value){this.$2=ss.Delegate.combine(this.$2,value);},remove_resizeStarted:function(value){this.$2=ss.Delegate.remove(this.$2,value);},$2:null,$3:function(){if(this.$2!=null){this.$2.invoke(this,new ss.EventArgs());}},add_resizeStopped:function(value){this.$4=ss.Delegate.combine(this.$4,value);},remove_resizeStopped:function(value){this.$4=ss.Delegate.remove(this.$4,value);},$4:null,$5:function(){if(this.$4!=null){this.$4.invoke(this,new ss.EventArgs());}},$9:null,panelId:null,isInitialized:false,get_rootContainerId:function(){return this.$9;},set_rootContainerId:function(value){this.$9=value;return value;},get_hasRootContainer:function(){return !String.isNullOrEmpty(this.get_rootContainerId());},initialize:function(){var $0=ss.Delegate.create(this,function($p1_0){
this.$A($p1_0);});var $1=String.format('\r\n$(\'{0}\').resizable({\r\n    handles: \'{1}\',\r\n    start: {2},\r\n    stop: {3},\r\n    resize: {4}\r\n    });\r\n',this.panelId,this.getHandles(),Open.Core.DelegateUtil.toEventCallbackString($0,'start'),Open.Core.DelegateUtil.toEventCallbackString($0,'eventStop'),Open.Core.DelegateUtil.toEventCallbackString($0,'eventResize'));eval($1);this.onInitialize();this.isInitialized=true;},onInitialize:function(){},onStarted:function(){},onResize:function(){},onStopped:function(){},onWindowSizeChanged:function(){},getPanel:function(){return $(this.panelId);},getRootContainer:function(){return (this.get_hasRootContainer())?$(this.get_rootContainerId()):null;},setResizeOption:function(option,value){var $0=String.format('$(\'{0}\').resizable(\'option\', \'{1}\', {2});',this.panelId,option,value);eval($0);},$A:function($p0){if($p0==='start'){this.onStarted();this.$3();}else if($p0==='eventResize'){this.onResize();this.$1();}else if($p0==='eventStop'){this.onStopped();this.$5();}}}
Open.Core.UI.VerticalPanelResizer=function(panelId){Open.Core.UI.VerticalPanelResizer.initializeBase(this,[panelId]);}
Open.Core.UI.VerticalPanelResizer.prototype={$C:0,$D:0,get_minHeight:function(){return this.$C;},set_minHeight:function(value){if(value===this.$C){return;}this.$C=value;this.$F();return value;},get_maxHeightMargin:function(){return this.$D;},set_maxHeightMargin:function(value){this.$D=value;return value;},getHandles:function(){return 'n';},onInitialize:function(){this.$E();},onStopped:function(){var $0=this.getPanel();$0.css('width',String.Empty);$0.css('top',String.Empty);},onWindowSizeChanged:function(){if(this.isInitialized){this.$E();}},$E:function(){this.$F();this.$10();},$F:function(){this.setResizeOption('minHeight',this.get_minHeight());},$10:function(){var $0=(this.get_hasRootContainer())?(this.getRootContainer().height()-this.get_maxHeightMargin()).toString():String.Empty;this.setResizeOption('maxHeight',$0);}}
Open.Core.Css.registerClass('Open.Core.Css');Open.Core.Events.registerClass('Open.Core.Events');Open.Core.DelegateUtil.registerClass('Open.Core.DelegateUtil');Open.Core.UI.PanelResizerBase.registerClass('Open.Core.UI.PanelResizerBase');Open.Core.UI.HorizontalPanelResizer.registerClass('Open.Core.UI.HorizontalPanelResizer',Open.Core.UI.PanelResizerBase);Open.Core.UI.VerticalPanelResizer.registerClass('Open.Core.UI.VerticalPanelResizer',Open.Core.UI.PanelResizerBase);Open.Core.Css.top='top';Open.Core.Css.bottom='bottom';Open.Core.Css.width='width';Open.Core.Css.height='height';Open.Core.Events.resize='resize';
// ---- Do not remove this footer ----
// This script was generated using Script# v0.6.0.0 (http://projects.nikhilk.net/ScriptSharp)
// -----------------------------------
}
ss.loader.registerScript('Open.Core.Script',[],executeScript);})();