// Open.Core.Test.js
(function(){function executeScript(){
Type.registerNamespace('Open.Core.Test.ViewTests');Open.Core.Test.ViewTests.DiContainerTest=function(){}
Open.Core.Test.ViewTests.DiContainerTest.prototype={$0:null,testInitialize:function(){this.$0=new Open.Core.DiContainer();},testCleanup:function(){this.$0.dispose();},shouldNotHaveSingleton:function(){Open.Core.Should.beNull(this.$0.getSingleton(Open.Core.Test.ViewTests.IMyInterface));},shouldHaveSingletonAfterRegistering:function(){var $0=new Open.Core.Test.ViewTests.MyClass();this.$0.registerSingleton(Open.Core.Test.ViewTests.IMyInterface,$0);var $1=this.$0.getSingleton(Open.Core.Test.ViewTests.IMyInterface);Open.Core.Should.equal($1,$0);},shouldReplaceSingleton:function(){var $0=new Open.Core.Test.ViewTests.MyClass();var $1=new Open.Core.Test.ViewTests.MyClass();this.$0.registerSingleton(Open.Core.Test.ViewTests.IMyInterface,$0);this.$0.registerSingleton(Open.Core.Test.ViewTests.IMyInterface,$1);var $2=this.$0.getSingleton(Open.Core.Test.ViewTests.IMyInterface);Open.Core.Should.notEqual($2,$0);Open.Core.Should.equal($2,$1);},shouldReturnNullWhenNoKeySpecified:function(){Open.Core.Should.beNull(this.$0.getSingleton(null));},shouldNotContainSingleton:function(){Open.Core.Should.beFalse(this.$0.containsSingleton(Open.Core.Test.ViewTests.IMyInterface));},shouldContainSingleton:function(){this.$0.registerSingleton(Open.Core.Test.ViewTests.IMyInterface,new Open.Core.Test.ViewTests.MyClass());Open.Core.Should.beTrue(this.$0.containsSingleton(Open.Core.Test.ViewTests.IMyInterface));},shouldUnregisterContainSingleton:function(){var $0=new Open.Core.Test.ViewTests.MyClass();this.$0.registerSingleton(Open.Core.Test.ViewTests.IMyInterface,$0);this.$0.registerSingleton(Open.Core.Test.ViewTests.IMyInterface,$0);Open.Core.Should.equal(this.$0.getSingleton(Open.Core.Test.ViewTests.IMyInterface),$0);this.$0.unregisterSingleton(Open.Core.Test.ViewTests.IMyInterface);Open.Core.Should.equal(this.$0.getSingleton(Open.Core.Test.ViewTests.IMyInterface),null);},shouldCreateSingletonInstance:function(){Open.Core.Should.beNull(this.$0.getSingleton(Open.Core.Test.ViewTests.IMyInterface));var $0=new Open.Core.Test.ViewTests.MyClass();var $1=this.$0.getOrCreateSingleton(Open.Core.Test.ViewTests.IMyInterface,ss.Delegate.create(this,function(){
return $0;}));Open.Core.Should.equal($1,$0);Open.Core.Should.equal(this.$0.getSingleton(Open.Core.Test.ViewTests.IMyInterface),$0);}}
Open.Core.Test.ViewTests.MyClass=function(){Open.Core.Test.ViewTests.MyClass.initializeBase(this);}
Open.Core.Test.ViewTests.IMyInterface=function(){}
Open.Core.Test.ViewTests.LoadHelperTest=function(){}
Open.Core.Test.ViewTests.LoadHelperTest.prototype={loadControls:function(){Open.Core.Log.info('Helper.ScriptLoader.IsLoaded: '+Open.Core.Helper.get_scriptLoader().isLoaded(0));Open.Core.Helper.get_scriptLoader().loadLibrary(0,ss.Delegate.create(this,function(){
Open.Core.Log.info('Callback - '+Open.Core.Helper.get_scriptLoader().isLoaded(0));}));Open.Core.Log.lineBreak();}}
Type.registerNamespace('Open.Core.Test');Open.Core.Test.Application=function(){}
Open.Core.Test.Application.main=function(args){Open.Testing.TestHarness.registerClass(Open.Core.Test.ViewTests.LoadHelperTest);Open.Testing.TestHarness.registerClass(Open.Core.Test.ViewTests.DiContainerTest);}
Open.Core.Test.ViewTests.DiContainerTest.registerClass('Open.Core.Test.ViewTests.DiContainerTest');Open.Core.Test.ViewTests.IMyInterface.registerClass('Open.Core.Test.ViewTests.IMyInterface');Open.Core.Test.ViewTests.MyClass.registerClass('Open.Core.Test.ViewTests.MyClass',Open.Core.Test.ViewTests.IMyInterface);Open.Core.Test.ViewTests.LoadHelperTest.registerClass('Open.Core.Test.ViewTests.LoadHelperTest');Open.Core.Test.Application.registerClass('Open.Core.Test.Application');
// ---- Do not remove this footer ----
// This script was generated using Script# v0.6.0.0 (http://projects.nikhilk.net/ScriptSharp)
// -----------------------------------
}
ss.loader.registerScript('Open.Core.Test',['Open.Core.Script'],executeScript);})();