// Open.Core.Test.js
(function(){function executeScript(){
Type.registerNamespace('Open.Core.Test');Open.Core.Test.SampleView=function(){Open.Core.Test.SampleView.initializeBase(this,[Open.Core.Html.createDiv()]);this.add_propertyChanged(ss.Delegate.create(this,function($p1_0,$p1_1){
this.lastPropertyChanged=$p1_1.get_property();}));}
Open.Core.Test.SampleView.prototype={lastPropertyChanged:null}
Open.Core.Test.SampleListItem=function(text){Open.Core.Test.SampleListItem.initializeBase(this);this.set_text(text);}
Open.Core.Test.SampleListItem.prototype={toString:function(){return Open.Core.Test.SampleListItem.callBaseMethod(this, 'toString');}}
Open.Core.Test.SampleModel=function(){Open.Core.Test.SampleModel.initializeBase(this);}
Open.Core.Test.Application=function(){}
Open.Core.Test.Application.main=function(args){Open.Testing.TestHarness.registerClass(Open.Core.Test.UnitTests.ScriptLoadHelperTest);Open.Testing.TestHarness.registerClass(Open.Core.Test.UnitTests.DiContainerTest);Open.Testing.TestHarness.registerClass(Open.Core.Test.UnitTests.ModelBaseUnitTest);Open.Testing.TestHarness.registerClass(Open.Core.Test.UnitTests.ViewBaseUnitTest);Open.Testing.TestHarness.registerClass(Open.Core.Test.ViewTests.Core.ViewBaseTest);Open.Testing.TestHarness.registerClass(Open.Core.Test.ViewTests.Lists.ListTreeTest);Open.Testing.TestHarness.registerClass(Open.Core.Test.ViewTests.Lists.ListItemViewTest);Open.Testing.TestHarness.registerClass(Open.Core.Test.ViewTests.Controls.LogTest);Open.Testing.TestHarness.registerClass(Open.Core.Test.ViewTests.Controls.Buttons.SystemButtonTest);Open.Testing.TestHarness.registerClass(Open.Core.Test.ViewTests.Controls.HtmlPrimitive.HtmlListTest);}
Type.registerNamespace('Open.Core.Test.UnitTests');Open.Core.Test.UnitTests.DiContainerTest=function(){}
Open.Core.Test.UnitTests.DiContainerTest.prototype={$0:null,testInitialize:function(){this.$0=new Open.Core.DiContainer();},testCleanup:function(){this.$0.dispose();},shouldNotHaveSingleton:function(){Open.Core.Should.beNull(this.$0.getSingleton(Open.Core.Test.UnitTests.IMyInterface));},shouldHaveSingletonAfterRegistering:function(){var $0=new Open.Core.Test.UnitTests.MyClass();this.$0.registerSingleton(Open.Core.Test.UnitTests.IMyInterface,$0);var $1=this.$0.getSingleton(Open.Core.Test.UnitTests.IMyInterface);Open.Core.Should.equal($1,$0);},shouldReplaceSingleton:function(){var $0=new Open.Core.Test.UnitTests.MyClass();var $1=new Open.Core.Test.UnitTests.MyClass();this.$0.registerSingleton(Open.Core.Test.UnitTests.IMyInterface,$0);this.$0.registerSingleton(Open.Core.Test.UnitTests.IMyInterface,$1);var $2=this.$0.getSingleton(Open.Core.Test.UnitTests.IMyInterface);Open.Core.Should.notEqual($2,$0);Open.Core.Should.equal($2,$1);},shouldReturnNullWhenNoKeySpecified:function(){Open.Core.Should.beNull(this.$0.getSingleton(null));},shouldNotContainSingleton:function(){Open.Core.Should.beFalse(this.$0.containsSingleton(Open.Core.Test.UnitTests.IMyInterface));},shouldContainSingleton:function(){this.$0.registerSingleton(Open.Core.Test.UnitTests.IMyInterface,new Open.Core.Test.UnitTests.MyClass());Open.Core.Should.beTrue(this.$0.containsSingleton(Open.Core.Test.UnitTests.IMyInterface));},shouldUnregisterSingleton:function(){var $0=new Open.Core.Test.UnitTests.MyClass();this.$0.registerSingleton(Open.Core.Test.UnitTests.IMyInterface,$0);this.$0.registerSingleton(Open.Core.Test.UnitTests.IMyInterface,$0);Open.Core.Should.equal(this.$0.getSingleton(Open.Core.Test.UnitTests.IMyInterface),$0);this.$0.unregisterSingleton(Open.Core.Test.UnitTests.IMyInterface);Open.Core.Should.equal(this.$0.getSingleton(Open.Core.Test.UnitTests.IMyInterface),null);},shouldCreateSingletonInstance:function(){Open.Core.Should.beNull(this.$0.getSingleton(Open.Core.Test.UnitTests.IMyInterface));var $0=new Open.Core.Test.UnitTests.MyClass();var $1=this.$0.getOrCreateSingleton(Open.Core.Test.UnitTests.IMyInterface,ss.Delegate.create(this,function(){
return $0;}));Open.Core.Should.equal($1,$0);Open.Core.Should.equal(this.$0.getSingleton(Open.Core.Test.UnitTests.IMyInterface),$0);}}
Open.Core.Test.UnitTests.MyClass=function(){Open.Core.Test.UnitTests.MyClass.initializeBase(this);}
Open.Core.Test.UnitTests.IMyInterface=function(){}
Open.Core.Test.UnitTests.ModelBaseUnitTest=function(){}
Open.Core.Test.UnitTests.ModelBaseUnitTest.prototype={$0:null,classInitialize:function(){},classCleanup:function(){},testInitialize:function(){this.$0=new Open.Core.Test.SampleModel();},testCleanup:function(){this.$0.dispose();},shouldNotBeDisposed:function(){Open.Core.Should.beFalse(this.$0.get_isDisposed());},shouldBeDisposed:function(){this.$0.dispose();Open.Core.Should.beTrue(this.$0.get_isDisposed());},shouldFireDisposedEventOnce:function(){var $0=0;this.$0.add_disposed(ss.Delegate.create(this,function(){
$0++;}));this.$0.dispose();this.$0.dispose();Open.Core.Should.equal($0,1);}}
Open.Core.Test.UnitTests.ScriptLoadHelperTest=function(){}
Open.Core.Test.UnitTests.ScriptLoadHelperTest.prototype={loadControls:function(){Open.Core.Log.info('Helper.ScriptLoader.IsLoaded: '+Open.Core.Helper.get_scriptLoader().isLoaded(0));Open.Core.Helper.get_scriptLoader().loadLibrary(0,ss.Delegate.create(this,function(){
Open.Core.Log.info('Callback - '+Open.Core.Helper.get_scriptLoader().isLoaded(0));}));}}
Open.Core.Test.UnitTests.ViewBaseUnitTest=function(){}
Open.Core.Test.UnitTests.ViewBaseUnitTest.prototype={$0:null,testInitialize:function(){this.$0=new Open.Core.Test.SampleView();Open.Testing.TestHarness.addControl(this.$0);},testCleanup:function(){this.$0.dispose();Open.Testing.TestHarness.reset();},shouldNotHaveBackground:function(){Open.Core.Should.beNull(this.$0.get_background());},shouldSetCssValue:function(){this.$0.set_background('orange');Open.Core.Should.equal(this.$0.get_background(),'orange');},shouldResetCssValueToNull:function(){this.$0.set_background('orange');this.$0.set_background('');Open.Core.Should.beNull(this.$0.get_background());},shouldFireBackgroundChangedEvent:function(){this.$0.lastPropertyChanged=null;this.$0.set_background('orange');Open.Core.Should.equal(this.$0.lastPropertyChanged.get_name(),Open.Core.ViewBase.propBackground);},shouldBeVisibleByDefault:function(){Open.Core.Should.beTrue(this.$0.get_isVisible());Open.Core.Should.equal(this.$0.getCss(Open.Core.Css.display),Open.Core.Css.block);},shouldSetDisplayToBlockWhenIsVisible:function(){this.$0.set_isVisible(false);this.$0.set_isVisible(true);Open.Core.Should.equal(this.$0.getCss(Open.Core.Css.display),Open.Core.Css.block);},shouldSetDisplayToNoneWhenNotIsVisible:function(){this.$0.set_isVisible(false);Open.Core.Should.equal(this.$0.getCss(Open.Core.Css.display),Open.Core.Css.none);},shouldFireVisibilityChangedEventsOnce:function(){var $0=0;var $1=0;this.$0.add_propertyChanged(ss.Delegate.create(this,function($p1_0,$p1_1){
if($p1_1.get_property().get_name()===Open.Core.ViewBase.propIsVisible){$0++;}}));this.$0.add_isVisibleChanged(ss.Delegate.create(this,function(){
$1++;}));this.$0.set_isVisible(false);this.$0.set_isVisible(false);this.$0.set_isVisible(false);Open.Core.Should.equal($0,1);Open.Core.Should.equal($1,1);},shouldBeFullOpacityByDefault:function(){Open.Core.Should.equal(this.$0.get_opacity(),1);},shouldBoundOpacityValue:function(){this.$0.set_opacity(2);Open.Core.Should.equal(this.$0.get_opacity(),1);this.$0.set_opacity(-1);Open.Core.Should.equal(this.$0.get_opacity(),0);},shouldSetOpacityCss:function(){this.$0.set_opacity(0.5);Open.Core.Should.equal(this.$0.getCss('opacity'),'0.5');},shouldChangeWidth:function(){var $0=0;this.$0.add_sizeChanged(ss.Delegate.create(this,function(){
$0++;}));Open.Core.Should.equal(this.$0.get_width(),0);this.$0.set_width(50);this.$0.set_width(50);Open.Core.Should.equal(this.$0.get_width(),50);Open.Core.Should.equal($0,1);},shouldChangeHeight:function(){var $0=0;this.$0.add_sizeChanged(ss.Delegate.create(this,function(){
$0++;}));Open.Core.Should.equal(this.$0.get_height(),0);this.$0.set_height(50);this.$0.set_height(50);Open.Core.Should.equal(this.$0.get_height(),50);Open.Core.Should.equal($0,1);},shouldSetSize:function(){this.$0.setSize(80,80);Open.Core.Should.equal(this.$0.get_width(),80);Open.Core.Should.equal(this.$0.get_height(),80);},shouldFireSizeChangedOnce:function(){var $0=0;this.$0.add_sizeChanged(ss.Delegate.create(this,function(){
$0++;}));this.$0.setSize(80,80);this.$0.setSize(80,80);Open.Core.Should.equal($0,1);},shouldNowAllowNegativeSizing:function(){this.$0.setSize(-1,-1);Open.Core.Should.equal(this.$0.get_width(),0);Open.Core.Should.equal(this.$0.get_height(),0);this.$0.set_width(-15);this.$0.set_height(-5);Open.Core.Should.equal(this.$0.get_width(),0);Open.Core.Should.equal(this.$0.get_height(),0);},shouldBeEnabledByDefault:function(){Open.Core.Should.beTrue(this.$0.get_isEnabled());},shouldFireIsEnabledChanged:function(){var $0=0;var $1=0;this.$0.add_isEnabledChanged(ss.Delegate.create(this,function(){
$0++;}));this.$0.add_propertyChanged(ss.Delegate.create(this,function($p1_0,$p1_1){
if($p1_1.get_property().get_name()===Open.Core.ViewBase.propIsEnabled){$1++;}}));this.$0.set_isEnabled(false);this.$0.set_isEnabled(false);this.$0.set_isEnabled(false);Open.Core.Should.beFalse(this.$0.get_isEnabled());Open.Core.Should.equal($0,1);Open.Core.Should.equal($1,1);this.$0.set_isEnabled(true);Open.Core.Should.beTrue(this.$0.get_isEnabled());Open.Core.Should.equal($0,2);Open.Core.Should.equal($1,2);}}
Type.registerNamespace('Open.Core.Test.ViewTests.Controls.Buttons');Open.Core.Test.ViewTests.Controls.Buttons.LogButtons=function(){}
Open.Core.Test.ViewTests.Controls.Buttons.LogButtons.writeIButton=function(button){Open.Core.Log.info('IsEnabled: '+button.get_isEnabled());Open.Core.Log.info('CanToggle: '+button.get_canToggle());Open.Core.Log.info('MouseState: '+Open.Core.ButtonMouseState.toString(button.get_mouseState()));Open.Core.Log.info('IsPressed: '+button.get_isPressed());Open.Core.Log.info('IsMouseOver: '+button.get_isMouseOver());Open.Core.Log.info('IsMouseDown: '+button.get_isMouseDown());}
Open.Core.Test.ViewTests.Controls.Buttons.LogButtons.writeSystemButton=function(button){Open.Core.Log.info('Html: '+button.get_html());Open.Core.Log.info('Type: '+button.get_type());Open.Core.Log.info('Value: '+button.get_value());Open.Core.Log.info('Padding: '+button.get_padding());Open.Core.Log.info('FontSize: '+button.get_fontSize());Open.Core.Test.ViewTests.Controls.Buttons.LogButtons.writeIButton(button);}
Open.Core.Test.ViewTests.Controls.Buttons.SystemButtonTest=function(){}
Open.Core.Test.ViewTests.Controls.Buttons.SystemButtonTest.prototype={$0:null,classInitialize:function(){this.$0=new Open.Core.Controls.Buttons.SystemButton();Open.Testing.TestHarness.addControl(this.$0);this.$0.add_click(ss.Delegate.create(this,function(){
Open.Core.Log.info('!! Click | IsPressed: '+this.$0.get_isPressed());}));this.$0.add_isPressedChanged(ss.Delegate.create(this,function(){
Open.Core.Log.info('!! IsPressedChanged | IsPressed: '+this.$0.get_isPressed());}));this.$0.add_propertyChanged(ss.Delegate.create(this,function($p1_0,$p1_1){
}));},classCleanup:function(){},testInitialize:function(){},testCleanup:function(){},toggle_IsEnabled:function(){this.$0.set_isEnabled(!this.$0.get_isEnabled());},change_Html:function(){this.$0.set_html((this.$0.get_html()===Open.Core.Controls.Buttons.SystemButton.untitled)?'My <b>Button</b>':Open.Core.Controls.Buttons.SystemButton.untitled);},change_Padding:function(){this.$0.set_padding((this.$0.get_padding()==null)?Open.Core.Controls.Buttons.SystemButton.defaultPadding:null);},change_FontSize:function(){this.$0.set_fontSize((this.$0.get_fontSize()==='40pt')?'8pt':'40pt');},invokeClick__Force:function(){this.$0.invokeClick(true);},invokeClick__Not_Forced:function(){this.$0.invokeClick(false);},canToggle_True__Error:function(){this.$0.set_canToggle(true);},write_Properties:function(){Open.Core.Test.ViewTests.Controls.Buttons.LogButtons.writeSystemButton(this.$0);}}
Type.registerNamespace('Open.Core.Test.ViewTests.Controls');Open.Core.Test.ViewTests.Controls.LogTest=function(){}
Open.Core.Test.ViewTests.Controls.LogTest.prototype={classInitialize:function(){},classCleanup:function(){},testInitialize:function(){},testCleanup:function(){},log__Info:function(){Open.Core.Log.info('Info');},log__Debug:function(){Open.Core.Log.debug('Debug');},log__Warning:function(){Open.Core.Log.warning('Warning');},log__Error:function(){Open.Core.Log.error('Error');},log__Null:function(){Open.Core.Log.info(null);},log__Empty_String:function(){Open.Core.Log.info('');},lineBreak:function(){Open.Core.Log.lineBreak();},newSection:function(){Open.Core.Log.newSection();},log_After_Delay:function(){Open.Core.DelayedAction.invoke(0.5,ss.Delegate.create(this,function(){
Open.Core.Log.info('Logged after delay');}));},clear:function(){Open.Core.Log.clear();},sample1:function(){Open.Core.Log.info('This is a log entry');Open.Core.Log.info('Another entry within the same test.');},sample2:function(){Open.Core.Log.info('This entry came from another test (Sample2).');Open.Core.Log.info('Note the section divider visually showing that these entries were emitted from different tests.');}}
Type.registerNamespace('Open.Core.Test.ViewTests.Controls.HtmlPrimitive');Open.Core.Test.ViewTests.Controls.HtmlPrimitive.HtmlListTest=function(){}
Open.Core.Test.ViewTests.Controls.HtmlPrimitive.HtmlListTest.$2=function($p0){return Open.Core.Helper.get_string().formatToString($p0,function($p1_0){
return $p0.html();});}
Open.Core.Test.ViewTests.Controls.HtmlPrimitive.HtmlListTest.prototype={$0:null,$1:0,classInitialize:function(){this.$0=new Open.Core.Controls.HtmlPrimitive.HtmlList(0,'myListClass');this.$0.get_container().css(Open.Core.Css.background,'orange');this.$0.get_container().width(300);Open.Testing.TestHarness.addControl(this.$0);this.add();this.add();},classCleanup:function(){},testInitialize:function(){},testCleanup:function(){},add:function(){this.$1++;var $0='Item '+this.$1;var $1=this.$0.add($0,'myClass1 myClass2');Open.Core.Log.info('Inserted item: '+Open.Core.Html.toHtml($1).htmlEncode());this.write_Properties();},removeAt_Zero:function(){this.$0.remove(0);this.write_Properties();},removeLast:function(){if(this.$0.get_last()!=null){this.$0.get_last().remove();}this.write_Properties();},clear:function(){this.$0.clear();this.write_Properties();},myERROR:function(){Open.Core.Log.info('Throwing error now.');throw new Error('Hello');},write_Properties:function(){Open.Core.Log.info('Count: '+this.$0.get_count());Open.Core.Log.info('ListType: '+Open.Core.HtmlListType.toString(this.$0.get_listType()));Open.Core.Log.info('First: '+Open.Core.Test.ViewTests.Controls.HtmlPrimitive.HtmlListTest.$2(this.$0.get_first()));Open.Core.Log.info('Last: '+Open.Core.Test.ViewTests.Controls.HtmlPrimitive.HtmlListTest.$2(this.$0.get_last()));Open.Core.Log.info('InnerHtml: '+this.$0.get_innerHtml().htmlEncode());Open.Core.Log.info('OuterHtml: '+this.$0.get_outerHtml().htmlEncode());}}
Type.registerNamespace('Open.Core.Test.ViewTests.Core');Open.Core.Test.ViewTests.Core.ViewBaseTest=function(){}
Open.Core.Test.ViewTests.Core.ViewBaseTest.prototype={$0:null,classInitialize:function(){this.$0=new Open.Core.Test.SampleView();this.$0.set_background('orange');this.$0.setSize(150,100);Open.Testing.TestHarness.addControl(this.$0);this.$0.add_sizeChanged(ss.Delegate.create(this,function(){
Open.Core.Log.info('!! SizeChanged - Width: '+this.$0.get_width()+', Height: '+this.$0.get_height());}));},classCleanup:function(){this.$0.dispose();},testInitialize:function(){},testCleanup:function(){},toggle__IsVisible:function(){this.$0.set_isVisible(!this.$0.get_isVisible());},toggle__Background:function(){this.$0.set_background((this.$0.get_background()==='orange')?'red':'orange');},toggle__Opacity:function(){this.$0.set_opacity((this.$0.get_opacity()===1)?0.3:1);Open.Core.Log.info('Opacity: '+this.$0.get_opacity());},change__Size:function(){if(this.$0.get_width()===150){this.$0.setSize(400,300);}else{this.$0.setSize(150,100);}}}
Type.registerNamespace('Open.Core.Test.ViewTests.Lists');Open.Core.Test.ViewTests.Lists.ListItemViewTest=function(){}
Open.Core.Test.ViewTests.Lists.ListItemViewTest.prototype={$0:null,$1:null,classInitialize:function(){this.$0=new Open.Core.Test.SampleListItem('My Item');this.$1=new Open.Core.Lists.ListItemView(Open.Core.Html.createDiv(),this.$0);this.$1.set_width(300);Open.Testing.TestHarness.addControl(this.$1);},classCleanup:function(){this.$1.dispose();},testInitialize:function(){},testCleanup:function(){},toggle__CanSelect:function(){this.$0.set_canSelect(!this.$0.get_canSelect());this.$2();},toggle__IsSelected:function(){var $0=!this.$0.get_isSelected();if(!this.$0.get_canSelect()&&$0){Open.Core.Log.info('New value is true.  Because \'CanSelect\' == false, the new value will not stick.');}this.$0.set_isSelected($0);this.$2();},$2:function(){Open.Core.Log.info('IsSelected: '+this.$0.get_isSelected());Open.Core.Log.info('CanSelect: '+this.$0.get_canSelect());}}
Open.Core.Test.ViewTests.Lists.ListTreeTest=function(){}
Open.Core.Test.ViewTests.Lists.ListTreeTest.prototype={$0:null,classInitialize:function(){this.$0=new Open.Core.Lists.ListTreeView(Open.Core.Html.createDiv());this.$0.setSize(250,500);this.$0.set_background('#f2f2f2');Open.Testing.TestHarness.addControl(this.$0);this.$0.add_selectedNodeChanged(ss.Delegate.create(this,function(){
Open.Core.Log.info('!! SelectedNodeChanged | SelectedNode: '+this.$0.get_selectedNode());}));this.$0.add_selectedParentChanged(ss.Delegate.create(this,function(){
Open.Core.Log.info('!! SelectedParentChanged | SelectedParent: '+this.$0.get_selectedParent());}));},classCleanup:function(){this.$0.dispose();},testInitialize:function(){},testCleanup:function(){},addNodes:function(){this.$1();},rootNode__Null:function(){this.$0.set_rootNode(null);},back:function(){this.$0.back();},home:function(){this.$0.home();},$1:function(){var $0=new Open.Core.Test.SampleListItem('Root');this.$0.set_rootNode($0);$0.addChild(new Open.Core.Test.SampleListItem('Child 1'));$0.addChild(new Open.Core.Test.SampleListItem('Child 2'));$0.addChild(new Open.Core.Test.SampleListItem('Child 3'));var $1=Type.safeCast($0.childAt(0),Open.Core.Test.SampleListItem);$1.addChild(new Open.Core.Test.SampleListItem('Recent Grandchild 1'));$1.addChild(new Open.Core.Test.SampleListItem('Recent Grandchild 2'));$1.addChild(new Open.Core.Test.SampleListItem('Recent Grandchild 3'));}}
Open.Core.Test.SampleView.registerClass('Open.Core.Test.SampleView',Open.Core.ViewBase);Open.Core.Test.SampleListItem.registerClass('Open.Core.Test.SampleListItem',Open.Core.Lists.ListItem);Open.Core.Test.SampleModel.registerClass('Open.Core.Test.SampleModel',Open.Core.ModelBase);Open.Core.Test.Application.registerClass('Open.Core.Test.Application');Open.Core.Test.UnitTests.DiContainerTest.registerClass('Open.Core.Test.UnitTests.DiContainerTest');Open.Core.Test.UnitTests.IMyInterface.registerClass('Open.Core.Test.UnitTests.IMyInterface');Open.Core.Test.UnitTests.MyClass.registerClass('Open.Core.Test.UnitTests.MyClass',Open.Core.Test.UnitTests.IMyInterface);Open.Core.Test.UnitTests.ModelBaseUnitTest.registerClass('Open.Core.Test.UnitTests.ModelBaseUnitTest');Open.Core.Test.UnitTests.ScriptLoadHelperTest.registerClass('Open.Core.Test.UnitTests.ScriptLoadHelperTest');Open.Core.Test.UnitTests.ViewBaseUnitTest.registerClass('Open.Core.Test.UnitTests.ViewBaseUnitTest');Open.Core.Test.ViewTests.Controls.Buttons.LogButtons.registerClass('Open.Core.Test.ViewTests.Controls.Buttons.LogButtons');Open.Core.Test.ViewTests.Controls.Buttons.SystemButtonTest.registerClass('Open.Core.Test.ViewTests.Controls.Buttons.SystemButtonTest');Open.Core.Test.ViewTests.Controls.LogTest.registerClass('Open.Core.Test.ViewTests.Controls.LogTest');Open.Core.Test.ViewTests.Controls.HtmlPrimitive.HtmlListTest.registerClass('Open.Core.Test.ViewTests.Controls.HtmlPrimitive.HtmlListTest');Open.Core.Test.ViewTests.Core.ViewBaseTest.registerClass('Open.Core.Test.ViewTests.Core.ViewBaseTest');Open.Core.Test.ViewTests.Lists.ListItemViewTest.registerClass('Open.Core.Test.ViewTests.Lists.ListItemViewTest');Open.Core.Test.ViewTests.Lists.ListTreeTest.registerClass('Open.Core.Test.ViewTests.Lists.ListTreeTest');
// ---- Do not remove this footer ----
// This script was generated using Script# v0.6.0.0 (http://projects.nikhilk.net/ScriptSharp)
// -----------------------------------
}
ss.loader.registerScript('Open.Core.Test',['Open.Core.Script','Open.Core.Lists','Open.Core.Views'],executeScript);})();