// TestHarness.Test.js
(function(){function executeScript(){
Type.registerNamespace('Test.Samples');Test.Samples.Canvas_Control_Insertion_Test=function(){}
Test.Samples.Canvas_Control_Insertion_Test.$0=function($p0){var $0=new Test.Samples.MyView($p0);Open.Testing.TestHarness.set_displayMode($p0);Open.Testing.TestHarness.addControl($0);Open.Core.Log.info('Control added. DisplayMode: '+Open.Testing.ControlDisplayMode.toString($p0));}
Test.Samples.Canvas_Control_Insertion_Test.prototype={add_Control__None:function(){Test.Samples.Canvas_Control_Insertion_Test.$0(0);},add_Control__Center:function(){Test.Samples.Canvas_Control_Insertion_Test.$0(1);},add_Control__Fill:function(){Test.Samples.Canvas_Control_Insertion_Test.$0(2);},add_Control__FillWithMargin:function(){Test.Samples.Canvas_Control_Insertion_Test.$0(3);},reset:function(){Open.Testing.TestHarness.reset();Open.Core.Log.title('Reset');Open.Core.Log.info('SizeMode: '+Open.Testing.ControlDisplayMode.toString(Open.Testing.TestHarness.get_displayMode()));}}
Test.Samples.MyView=function(controlDisplayMode){Test.Samples.MyView.initializeBase(this);this.get_container().append(String.format('Control [sizeMode:{0}]',Open.Testing.ControlDisplayMode.toString(controlDisplayMode)));this.get_container().css(Open.Core.Css.background,'#f0ebc5');this.get_container().css(Open.Core.Css.width,'300px');this.get_container().css(Open.Core.Css.height,'200px');this.get_container().css('-webkit-border-radius','10px');this.get_container().css('-moz-border-radius','10px');this.get_container().css('border-radius','10px');}
Test.Samples.ConstructorParams=function(myParam){}
Test.Samples.ConstructorParams.prototype={test1:function(param1,param2){Open.Core.Log.title('Test1');Open.Core.Log.info('param1: '+param1);Open.Core.Log.info('param2: '+param2);Open.Core.Log.lineBreak();},test2:function(){},test3:function(){},test4:function(){}}
Test.Samples.CssTest=function(){}
Test.Samples.CssTest.$1=function($p0){var $0=new Test.Samples.MyCssView(Open.Core.Html.createDiv(),$p0);Open.Testing.TestHarness.set_displayMode($p0);Open.Testing.TestHarness.addControl($0);return $0;}
Test.Samples.CssTest.prototype={$0:null,testInitialize:function(){this.$0=Test.Samples.CssTest.$1(1);},perspective:function(){this.$0.apply('transform','perspective(500px);');}}
Test.Samples.MyCssView=function(container,controlDisplayMode){Test.Samples.MyCssView.initializeBase(this,[container]);container.append(String.format('Control [sizeMode:{0}]',Open.Testing.ControlDisplayMode.toString(controlDisplayMode)));container.css(Open.Core.Css.background,'#f0ebc5');container.css(Open.Core.Css.width,'300px');container.css(Open.Core.Css.height,'200px');container.css('-webkit-border-radius','10px');container.css('-moz-border-radius','10px');container.css('border-radius','10px');}
Test.Samples.MyCssView.prototype={apply:function(prop,value){this.get_container().css(prop,value);Open.Core.Log.info(String.format('{0}: {1}',prop,value));}}
Test.Samples.MyTest_Class__2=function(){}
Test.Samples.MyTest_Class__2.prototype={test1:function(){Open.Core.Log.info('MyTestClass2 : Test 1 Invoked');}}
Test.Samples.MyTestClass1=function(){}
Test.Samples.MyTestClass1.prototype={classInitialize:function(){Open.Core.Log.info('Class Initialize: '+Type.getInstanceType(this).get_name());},classCleanup:function(){Open.Core.Log.info('Class Cleanup: '+Type.getInstanceType(this).get_name());},testInitialize:function(){Open.Core.Log.info('Test Initialize');},testCleanup:function(){Open.Core.Log.info('Test Cleanup');},publicField:'Foo',$0:'Foo',get_publicProperty:function(){return this.publicField;},set_publicProperty:function(value){this.publicField=value;return value;},get_$1:function(){return this.$0;},set_$1:function($p0){this.$0=$p0;return $p0;},test1:function(){Open.Core.Log.info('MyTestClass1 : Test 1 Invoked');},test_Two:function(){Open.Core.Log.info('MyTestClass1 : Test 2 Invoked');},test__Three:function(){Open.Core.Log.info('MyTestClass1 : Test 3 Invoked');},contains_Error:function(){throw new Error('My error.');},removeStart:function(){Open.Core.Log.info(Open.Core.Helper.get_url().prependDomain('/MyPath'));Open.Core.Log.info(Open.Core.Helper.get_url().prependDomain('MyPath'));},write_Url:function(){Open.Core.Log.info('Hash: '+window.location.hash);Open.Core.Log.info('Hostname: '+window.location.hostname);Open.Core.Log.info('HostnameAndPort: '+window.location.host);Open.Core.Log.info('Href: '+window.location.href);Open.Core.Log.info('Pathname: '+window.location.pathname);Open.Core.Log.info('Port: '+window.location.port);Open.Core.Log.info('Protocol: '+window.location.protocol);Open.Core.Log.info('Search: '+window.location.search);},$2:function(){}}
Type.registerNamespace('Test');Test.Application=function(){}
Test.Application.main=function(args){Open.Testing.TestHarness.registerClass(Test.Samples.MyTestClass1);Open.Testing.TestHarness.registerClass(Test.Samples.MyTestClass1);Open.Testing.TestHarness.registerClass(Test.Samples.MyTest_Class__2);Open.Testing.TestHarness.registerClass(Test.Samples.Canvas_Control_Insertion_Test);Open.Testing.TestHarness.registerClass(Test.Samples.ConstructorParams);Open.Testing.TestHarness.registerClass(Test.Samples.CssTest);}
Test.Samples.Canvas_Control_Insertion_Test.registerClass('Test.Samples.Canvas_Control_Insertion_Test');Test.Samples.MyView.registerClass('Test.Samples.MyView',Open.Core.ViewBase);Test.Samples.ConstructorParams.registerClass('Test.Samples.ConstructorParams');Test.Samples.CssTest.registerClass('Test.Samples.CssTest');Test.Samples.MyCssView.registerClass('Test.Samples.MyCssView',Open.Core.ViewBase);Test.Samples.MyTest_Class__2.registerClass('Test.Samples.MyTest_Class__2');Test.Samples.MyTestClass1.registerClass('Test.Samples.MyTestClass1');Test.Application.registerClass('Test.Application');
// ---- Do not remove this footer ----
// This script was generated using Script# v0.6.0.0 (http://projects.nikhilk.net/ScriptSharp)
// -----------------------------------
}
ss.loader.registerScript('TestHarness.Script.Test',['Open.Core.Script'],executeScript);})();