// Open.Core.Lists.js
(function(){function executeScript(){
Type.registerNamespace('Open.Core.Lists');Open.Core.Lists.IListItemView=function(){};Open.Core.Lists.IListItemView.registerInterface('Open.Core.Lists.IListItemView');Open.Core.Lists.ListSelectionMode=function(){};Open.Core.Lists.ListSelectionMode.prototype = {none:0,single:1}
Open.Core.Lists.ListSelectionMode.registerEnum('Open.Core.Lists.ListSelectionMode',false);Open.Core.Lists.ListCss=function(){}
Open.Core.Lists.ListCss.insertCss=function(){if(Open.Core.Lists.ListCss.$0){return;}if(!Open.Core.Css.isLinked('/Open.Core/Css/Core.Lists.css')){Open.Core.Css.insertLink('/Open.Core/Css/Core.Lists.css');}Open.Core.Lists.ListCss.$0=true;}
Open.Core.Lists.ListCssClasses=function(){}
Open.Core.Lists.ListCssClasses.prototype={listItem:'coreListItem',selectedListItem:'selectedListItem',itemLabel:'itemLabel'}
Open.Core.Lists.List=function(container){this.$1_4=1;this.$1_5=[];Open.Core.Lists.List.initializeBase(this);this.initialize(container);Open.Core.Lists.ListCss.insertCss();}
Open.Core.Lists.List.prototype={add_selectionChanged:function(value){this.$1_0=ss.Delegate.combine(this.$1_0,value);},remove_selectionChanged:function(value){this.$1_0=ss.Delegate.remove(this.$1_0,value);},$1_0:null,$1_1:function(){if(this.$1_0!=null){this.$1_0.invoke(this,new ss.EventArgs());}},$1_2:null,$1_3:null,$1_6:function($p0,$p1){if(this.get_selectionMode()===0){return;}this.$1_7(Type.safeCast($p1,Open.Core.Lists.IListItemView));},get_itemFactory:function(){return this.$1_2||(this.$1_3||(this.$1_3=new Open.Core.Lists.OpenCoreLists$0()));},set_itemFactory:function(value){this.$1_2=value;return value;},get_selectionMode:function(){return this.$1_4;},set_selectionMode:function(value){this.$1_4=value;return value;},get_count:function(){return this.$1_5.length;},onInitialize:function(container){},load:function(items){this.clear();if(ss.isNullOrUndefined(items)){return;}var $0=Open.Core.Helper.get_collection().toArrayList(items);for(var $2=0;$2<$0.length;$2++){var $3=Open.Core.Html.appendDiv(this.get_container());$3.appendTo(this.get_container());}var $1=this.get_itemFactory();this.get_container().children(Open.Core.Html.div).each(ss.Delegate.create(this,function($p1_0,$p1_1){
var $1_0=$($p1_1);var $1_1=$0[$p1_0];var $1_2=$1.createView($1_0,$1_1);this.$1_5.add($1_2);$1_0.click(ss.Delegate.create(this,function($p2_0){
this.$1_6($p2_0,$1_2);}));}));},clear:function(){var $enum1=ss.IEnumerator.getEnumerator(this.$1_5);while($enum1.moveNext()){var $0=$enum1.get_current();$0.dispose();}this.get_container().empty();this.$1_5.clear();},select:function(model){if(ss.isNullOrUndefined(model)){return;}this.$1_7(this.$1_A(model));this.$1_1();},selectFirst:function(){this.selectIndex(0);},selectLast:function(){if(this.$1_5.length>0){this.selectIndex(this.$1_5.length-1);}},selectIndex:function(index){if(this.$1_5.length===0||index>this.$1_5.length-1||index<0){return;}this.$1_7(Type.safeCast(this.$1_5[index],Open.Core.Lists.IListItemView));},$1_7:function($p0){if(ss.isNullOrUndefined($p0)){return;}this.$1_8();$p0.set_isSelected(true);},$1_8:function(){var $enum1=ss.IEnumerator.getEnumerator(this.$1_9());while($enum1.moveNext()){var $0=$enum1.get_current();$0.set_isSelected(false);}},$1_9:function(){var $0=new Array(this.$1_5.length);var $enum1=ss.IEnumerator.getEnumerator(this.$1_5);while($enum1.moveNext()){var $1=$enum1.get_current();var $2=Type.safeCast($1,Open.Core.Lists.IListItemView);if(!ss.isNullOrUndefined($2)){$0.add($2);}}return $0;},$1_A:function($p0){var $enum1=ss.IEnumerator.getEnumerator(this.$1_9());while($enum1.moveNext()){var $0=$enum1.get_current();if($0.get_model()===$p0){return $0;}}return null;}}
Open.Core.Lists.ListItemView=function(liElement,model){Open.Core.Lists.ListItemView.initializeBase(this);this.$1_0=model;this.initialize(liElement);}
Open.Core.Lists.ListItemView.prototype={$1_0:null,$1_1:false,get_isSelected:function(){return this.$1_1;},set_isSelected:function(value){if(value===this.$1_1){return;}this.$1_1=value;this.$1_2();return value;},get_model:function(){return this.$1_0;},onInitialize:function(container){container.addClass(Open.Core.Lists.ListCss.classes.listItem);var $0=this.$1_0.get_text();var $1=$(String.format('<span>{0}</span>',(ss.isNullOrUndefined($0))?'No Text':$0));$1.appendTo(container);$1.addClass(Open.Core.Lists.ListCss.classes.itemLabel);$1.addClass(Open.Core.Css.classes.titleFont);},$1_2:function(){if(this.get_isSelected()){this.get_container().addClass(Open.Core.Lists.ListCss.classes.selectedListItem);}else{this.get_container().removeClass(Open.Core.Lists.ListCss.classes.selectedListItem);}}}
Open.Core.Lists.OpenCoreLists$0=function(){}
Open.Core.Lists.OpenCoreLists$0.prototype={createView:function($p0,$p1){return new Open.Core.Lists.ListItemView($p0,$p1);}}
Open.Core.Lists.ListCss.registerClass('Open.Core.Lists.ListCss');Open.Core.Lists.ListCssClasses.registerClass('Open.Core.Lists.ListCssClasses');Open.Core.Lists.List.registerClass('Open.Core.Lists.List',Open.Core.ViewBase);Open.Core.Lists.ListItemView.registerClass('Open.Core.Lists.ListItemView',Open.Core.ViewBase,Open.Core.Lists.IListItemView);Open.Core.Lists.OpenCoreLists$0.registerClass('Open.Core.Lists.OpenCoreLists$0',null,Open.Core.IViewFactory);Open.Core.Lists.ListCss.url='/Open.Core/Css/Core.Lists.css';Open.Core.Lists.ListCss.$0=false;Open.Core.Lists.ListCss.classes=new Open.Core.Lists.ListCssClasses();
// ---- Do not remove this footer ----
// This script was generated using Script# v0.6.0.0 (http://projects.nikhilk.net/ScriptSharp)
// -----------------------------------
}
ss.loader.registerScript('Open.Core.Lists',['Open.Core.Script'],executeScript);})();