// Open.Library.Jit.js
(function(){function executeScript(){
Type.registerNamespace('Open.Library.Jit');Open.Library.Jit.$create_HypertreeNode=function(id,name){var $o={};$o.id=id;$o.name=name;$o.children=[];return $o;}
Open.Library.Jit.JitCss=function(){}
Open.Library.Jit.Elements=function(){}
Open.Library.Jit.Hypertree=function(containerElement){if(containerElement==null){throw new Error('Container element not specified');}this.$3=containerElement;if(!Open.Core.Css.isLinked('/Open.Core/Css/Jit.Hypertree.css')){Open.Core.Css.insertLink('/Open.Core/Css/Jit.Hypertree.css');}$(window).bind(Open.Core.DomEvents.resize,ss.Delegate.create(this,function($p1_0){
this.$6();}));}
Open.Library.Jit.Hypertree.prototype={add_selectedNodeChanged:function(value){this.$0=ss.Delegate.combine(this.$0,value);},remove_selectedNodeChanged:function(value){this.$0=ss.Delegate.remove(this.$0,value);},$0:null,$1:function(){if(this.$0!=null){this.$0.invoke(this,new ss.EventArgs());}},$2:null,$3:null,$4:false,$5:null,onNodeClick:function(node){this.set_selectedNode(node);},get_selectedNode:function(){return this.$5;},set_selectedNode:function(value){if(value===this.get_selectedNode()){return;}this.$5=value;this.$1();return value;},initialize:function(callback){Open.Core.Helper.get_scriptLoader().get_jit().loadHypertree(ss.Delegate.create(this,function(){
var $1_0=this.$3.attr('id');this.$2=insertTree(this, $1_0);this.$6();this.$4=true;Open.Core.Helper.invokeOrDefault(callback);}));},load:function(rootNode){if(!this.$4){throw new Error('HyperTree not initialized');}this._hyperTree.loadJSON(rootNode);this.set_selectedNode(rootNode);this.refresh();},refresh:function(){if(!this.$4){return;}this._hyperTree.refresh();this._hyperTree.controller.onAfterCompute();},$6:function(){if(!this.$4){return;}var $0=this.$7();this._hyperTree.canvas.resize($0.get_width(), $0.get_height());this.refresh();if(this.get_selectedNode()!=null){this._hyperTree.onClick(this.get_selectedNode().id);}},$7:function(){return new Open.Core.Size(this.$3.width(),this.$3.height());}}
Open.Library.Jit.HypertreeNodeFactory=function(){}
Open.Library.Jit.HypertreeNodeFactory.create=function(json){var $0=Open.Library.Jit.$create_HypertreeNode(json['Id'],Type.safeCast(json['Name'],String));$0.data=json['Data'];var $1=Type.safeCast(json['Children'],Array);if(!ss.isNullOrUndefined($1)){var $enum1=ss.IEnumerator.getEnumerator($1);while($enum1.moveNext()){var $2=$enum1.get_current();$0.children.add(Open.Library.Jit.HypertreeNodeFactory.create($2));}}return $0;}
Open.Library.Jit.JitCss.registerClass('Open.Library.Jit.JitCss');Open.Library.Jit.Elements.registerClass('Open.Library.Jit.Elements');Open.Library.Jit.Hypertree.registerClass('Open.Library.Jit.Hypertree');Open.Library.Jit.HypertreeNodeFactory.registerClass('Open.Library.Jit.HypertreeNodeFactory');Open.Library.Jit.JitCss.hypertreeUrl='/Open.Core/Css/Jit.Hypertree.css';Open.Library.Jit.HypertreeNodeFactory.propId='Id';Open.Library.Jit.HypertreeNodeFactory.propName='Name';Open.Library.Jit.HypertreeNodeFactory.propChildren='Children';Open.Library.Jit.HypertreeNodeFactory.propData='Data';
// ---- Do not remove this footer ----
// This script was generated using Script# v0.6.0.0 (http://projects.nikhilk.net/ScriptSharp)
// -----------------------------------
}
ss.loader.registerScript('Open.Library.Jit',['Open.Core.Script'],executeScript);})();